# Generated by Django 5.2.1 on 2025-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'sales'), ('employee', 'Employee')], default='admin', max_length=50),
        ),
    ]
